remote_theme: pages-themes/modernist@v0.2.0
excerpt_separator: <!--more-->
permalink: none
baseurl: /c64wrd/
plugins:
- jekyll-remote-theme
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
